apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # 名字必需与下面的 spec 字段匹配，并且格式为 '<名称的复数形式>.<组名>'
  name: dbconfigs.api.practice.com
spec:
  # 分组名，在REST API中也会用到的，格式是: /apis/分组名/CRD版本
  group: api.practice.com
  # 列举此 CustomResourceDefinition 所支持的版本
  versions:
    - name: v1
      # 是否有效
      served: true
      storage: true
      additionalPrinterColumns: # 增加命令行显示的字段
        - name: Ready
          type: string
          jsonPath: .status.ready
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: MaxOpenConn
          type: integer
          jsonPath: .spec.maxOpenConn
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: # crd的期望状态
              type: object
              properties: # 需要的字段
                replicas:
                  type: integer
                  minimum: 1 # 设置最大与最小值
                  maximum: 20
                maxOpenConn:
                  type: integer
                  minimum: 1
                  maximum: 2000
                  default: 15
                maxIdleConn:
                  type: integer
                  minimum: 1
                  maximum: 2000
                  default: 5
                maxLifeTime:
                  type: integer
                  minimum: 60   #最小60秒
                  default: 600  #默认10分钟
                dsn:
                  type: string
              required: # 设置必填字段。
                - replicas
                - dsn
            status: # crd的实际状态
              type: object
              properties:
                 replicas:
                   type: integer
                 ready:
                   type: string
      subresources: # subresources 描述定制资源的子资源
        status: { } # status 启用 status 子资源
        scale:
          # specReplicasPath 定义定制资源中对应 scale.spec.replicas 的 JSON 路径
          specReplicasPath: .spec.replicas
          # statusReplicasPath 定义定制资源中对应 scale.status.replicas 的 JSON 路径
          statusReplicasPath: .status.replicas
  # 范围是属于namespace的 ,可以是 Namespaced 或 Cluster
  scope: Namespaced
  names:
    # 复数名
    plural: dbconfigs
    # 单数名
    singular: dbconfig
    # 类型名
    kind: DbConfig
    listKind: DbConfigList
    # kind的简称，就像service的简称是svc
    shortNames:
      - dc


# 附注：如果要修改或新增crd中的字段。分为以下几步：
# 1. 修改crd定义
# 2. 修改printColumn显示
# 3. 修改types.go文件
# 4. 如果有对应的业务逻辑，需要进行修改，ex: 模版内渲染与解析
